### ISSUE TITLE
rsyslog Service Not Found on Amazon Linux 2023 Instances

### ISSUE THREAD

**Issue by sambhaji1993** [chialab/aws-autoscaling-gitlab-runner#21]
Description: I am encountering an issue where the rsyslog service is not found on Amazon Linux 2023 instances. The service seems to be missing or not installed by default, causing errors during the initialization process when attempting to enable or start the service.

Steps to Reproduce:

Launch an Amazon Linux 2023 EC2 instance.

Attempt to check the status of the rsyslog service using the command:

**Comment by fquffio** [comment]
Hi, the legacy Docker machine based autoscaling executor has been deprecated by GitLab, therefore we're marking this project as abandoned.

We advise to migrate to the new autoscaling executor that uses fleeting plugins. See [docs](https://docs.gitlab.com/runner/executors/docker_autoscaler.html) here.
