### ISSUE TITLE
zoneinfo.zip: no such file or directory error when using OffPeakTimezone

### ISSUE THREAD

**Issue by mpgo13** [chialab/aws-autoscaling-gitlab-runner#8]
I had the following issue, documented here: https://docs.gitlab.com/runner/faq/#zoneinfozip-no-such-file-or-directory-error-when-using-offpeaktimezone

Used the newest AMI as described in this [comment](https://github.com/chialab/aws-autoscaling-gitlab-runner/issues/6#issuecomment-436703367)

**Comment by fquffio** [comment]
Closing as #9 has been merged. Thanks for your contribution!
